---
title: "RDD Replication 1"
author: "Megan Ellertson"
date: "2/14/2021"
output:
  pdf_document: default
  html_document: default
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library set up}
library(readr)
library(tidyverse)
library(ggplot2)
library(readr)
library(dplyr)
library(tidyr)
library(rdd)
library(haven)
library(estimatr)
library(rdrobust)
library(rddensity)
library(cli)

```

Question 1

```{r }

raw_hansen_dwi <- read_csv("Data/hansen_dwi.csv")

```

Question 2 
**Summary**

Question 3

```{r dummy variable creation}
RDDdata <- mutate(raw_hansen_dwi, cutoff = car::Recode(bac1, "lo: 0.08= 0; else = 1"))
head(RDDdata)

``` 
Question 4 

```{r mylatextable, results = "asis"}
stargazer(RDDdata, type = 'latex')

```



```{r}
figure1 <- ggplot(RDDdata, aes(bac1)) +
  geom_histogram(binwidth = 0.001, color = "grey", fill = "white") 
figure1 + geom_vline(aes(xintercept = 0.08), color = "black", size = 1) +
  geom_vline(aes(xintercept = 0.15), color = "black", size = 1) +
  labs(title = "BAC Histogram", x = "bac1", y = "Frequency")
```

```{r}

DCdensity(RDDdata$bac1, cutpoint = 0.08)

density <- rddensity(RDDdata$bac1, c = 0.08)
rdplotdensity(density, RDDdata$bac1)
```

Question 5 
```{r} 
## THIS IS THE RIGHT ONE. 
malecov <- RDestimate(formula = male ~ bac1 | aged + acc + white + cutoff + bac1*cutoff, data = RDDdata, cutpoint = 0.08, bw = 0.05, kernel = "rectangular")


agecov <- RDestimate(formula = aged ~ bac1 | male + acc + white + cutoff + bac1*cutoff, data = RDDdata, cutpoint = 0.08, bw = 0.05, kernel = "rectangular")


acccov <- RDestimate(formula = acc ~ bac1 | aged + male + white + cutoff + bac1*cutoff, data = RDDdata, cutpoint = 0.08, bw = 0.05, kernel = "rectangular")

whitecov <- RDestimate(formula = white ~ bac1 | aged + male + acc + cutoff + bac1*cutoff, data = RDDdata, cutpoint = 0.08, bw = 0.05, kernel = "rectangular")

data.frame(male = malecov$est[1], age = agecov$est[1], accident = acccov$est[1], white = whitecov$est[1])


```


Question 6
```{r echo = FALSE}
cli::cli_text("testing")
ggplot(data = RDDdata) +
geom_point(alpha = 0.5) +
geom_vline(xintercept = 0.8, color = "black", linetype = 1)+


```


Question 7
```{r}
## Panel A


RDDdata_subset1 <- RDDdata %>% 
  filter(bac1>0.03 & bac1 < 0.13)

lm_1 <- lm_robust(recidivism ~ bac1, data = RDDdata_subset1)
lm_2 <- lm_robust(recidivism ~ bac1*cutoff, data = RDDdata_subset1)
RDDdata_subset1a <- RDDdata_subset1 %>%
  mutate(bac1sq = bac1^2)
lm_3 <- lm_robust(recidivism ~ bac1*cutoff + bac1sq*cutoff, data = RDDdata_subset1a)

summary(lm_1)
summary(lm_2)
summary(lm_3)

## Panel B 
RDDdata_subset2 <- RDDdata %>% 
  filter(bac1>0.055 & bac1 < 0.105)

lm_4 <- lm_robust(recidivism ~ bac1, data = RDDdata_subset2)
lm_5 <- lm_robust(recidivism ~ bac1 + cutoff + bac1*cutoff, data = RDDdata_subset2)
RDDdata_subset2a <- RDDdata_subset2 %>%
  mutate(bac1sq = bac1^2)
lm_6 <- lm_robust(recidivism ~ bac1*cutoff + bac1sq*cutoff, data = RDDdata_subset2a)

summary(lm_4)
summary(lm_5)
summary(lm_6)

cli::cli_text("Table 3")
texreg::screenreg(list(lm_1, lm_2, lm_3, lm_4, lm_5, lm_6), type="text")

```


Question 8
```{r}
categories <- RDDdata$bac1 
demmeans <- split(RDDdata$recidivism, cut(RDDdata$bac1, 100)) %>%
  lapply(mean) %>%
  unlist()
agg_RDDdata <- data.frame(recidivism = demmeans, bac1 = seq(0.01, 0.5, by = 0.01))
plottingdata <- RDDdata %>%
  mutate(gg_group = case_when(bac1>= 0.08 ~ 1, TRUE ~ 0))

ggplot(plottingdata, aes(bac1, recidivism)) +
  geom_point(aes(x=bac1, y = recidivism), data = agg_RDDdata) + xlim(0, 0.2) + ylim(0.08, 0.16) +
  stat_smooth(aes(bac1, recidivism, group = gg_group), method = "lm", formula = y ~ x + I(x^2)) +
  xlim(0,0.2) + ylim(0,.25) +
  geom_vline(xintercept = 0.08)

ggplot(plottingdata, aes(bac1, recidivism)) +
  geom_point(aes(x=bac1, y = recidivism), data = agg_RDDdata) +
  stat_smooth(aes(bac1, recidivism, group = gg_group), method = "lm") +
  geom_vline(xintercept = 0.08)
  
```


Question 9

```{r}

```


